version: 2.1

executors:
  default:
    docker:
      - image: hashicorp/terraform:latest
    resource_class: medium

jobs:
  setup:
    executor: default
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            apt-get update && apt-get install -y unzip curl jq sudo software-properties-common gnupg
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            aws --version

  deploy:
    executor: default
    steps:
      - checkout
      - run:
          name: Terraform Init & Apply
          command: |
            terraform init
            terraform apply -auto-approve

workflows:
  version: 2
  build-deploy:
    jobs:
      - setup
      - deploy:
          requires:
            - setup
