version: 2.1

executors:
  default:
    docker:
      - image: ubuntu:latest
    resource_class: medium

jobs:
  setup:
    executor: default
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            export DEBIAN_FRONTEND=noninteractive
            apt-get update && apt-get install -y unzip curl jq software-properties-common
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            export PATH="/usr/local/bin:$PATH"
            aws --version
            apt-get install -y gnupg software-properties-common
            curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo tee /usr/share/keyrings/hashicorp-archive-keyring.gpg > /dev/null
            echo "deb [signed-by=/usr/share/keyrings/hashicorp-archive-keyring.gpg] https://apt.releases.hashicorp.com $(lsb_release -cs) main" | sudo tee /etc/apt/sources.list.d/hashicorp.list
            apt-get update && apt-get install -y terraform
            terraform --version

  deploy:
    executor: default
    steps:
      - checkout
      - run:
          name: Terraform Init & Apply
          command: |
            terraform init
            terraform apply -auto-approve

workflows:
  version: 2
  build-deploy:
    jobs:
      - setup
      - deploy:
          requires:
            - setup
