version: 2.1

executors:
  ubuntu:
    docker:
      - image: ubuntu:latest
    resource_class: medium

jobs:
  setup:
    executor: ubuntu
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            export DEBIAN_FRONTEND=noninteractive
            apt-get update && apt-get install -y tzdata unzip curl jq sudo software-properties-common gnupg
            ln -fs /usr/share/zoneinfo/Etc/UTC /etc/localtime
            dpkg-reconfigure --frontend noninteractive tzdata
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            aws --version

  terraform:
    docker:
      - image: hashicorp/terraform:latest
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Terraform Init & Apply
          command: |
            terraform init
            terraform apply -auto-approve

workflows:
  version: 2
  build-deploy:
    jobs:
      - setup
      - terraform:
          requires:
            - setup
