version: 2.1

jobs:
  setup:
    docker:
      - image: hashicorp/terraform:latest
    resource_class: medium
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            apt-get update && apt-get install -y unzip curl jq sudo software-properties-common gnupg
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            sudo ./aws/install
            aws --version
      - run:
          name: Configure AWS Credentials
          command: |
            echo "Configuring AWS Credentials..."
            mkdir -p ~/.aws
            echo "[default]" > ~/.aws/credentials
            echo "aws_access_key_id=$AWS_ACCESS_KEY_ID" >> ~/.aws/credentials
            echo "aws_secret_access_key=$AWS_SECRET_ACCESS_KEY" >> ~/.aws/credentials
            echo "[default]" > ~/.aws/config
            echo "region=$AWS_REGION" >> ~/.aws/config
            cat ~/.aws/credentials
      - run:
          name: Terraform Init & Apply
          command: |
            terraform init
            terraform apply -auto-approve

workflows:
  version: 2
  terraform:
    jobs:
      - setup
