version: 2.1

jobs:
  setup:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            export DEBIAN_FRONTEND=noninteractive
            apt-get update && apt-get install -y unzip curl jq software-properties-common tzdata
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            ./aws/install
            aws --version

  deploy:
    docker:
      - image: hashicorp/terraform:latest
    steps:
      - checkout
      - run:
          name: Install Terraform
          command: |
            terraform --version
      - run:
          name: Terraform Init & Apply
          command: |
            terraform init
            terraform apply -auto-approve

workflows:
  version: 2
  build-deploy:
    jobs:
      - setup
      - deploy:
          requires:
            - setup
