version: 2.1

jobs:
  setup:
    docker:
      - image: python:3.9  # Usamos Python en Debian para compatibilidad
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: |
            apt-get update && apt-get install -y unzip curl jq
            curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
            unzip awscliv2.zip
            ./aws/install
            aws --version
      - run:
          name: Install Terraform
          command: |
            curl -fsSL https://apt.releases.hashicorp.com/gpg | apt-key add -
            apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"
            apt-get update && apt-get install -y terraform
            terraform -version
      - persist_to_workspace:
          root: .
          paths:
            - .

  terraform_apply:
    docker:
      - image: hashicorp/terraform:1.5
    steps:
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Initialize Terraform
          command: terraform init
      - run:
          name: Validate Terraform Configuration
          command: terraform validate
      - run:
          name: Apply Terraform Configuration
          command: terraform apply -auto-approve

workflows:
  version: 2
  deploy:
    jobs:
      - setup
      - terraform_apply:
          requires:
            - setup
